collections:
  stops:
    output: true
    permalink: /stop/:title
title: Fowey Art Trail
description: Map of exhibitors for this year's Art Trail in Fowey
url: foweyarttrail.com
author: Hazel Bradish
