collections:
  stops:
    output: true
    permalink: /stop/:title.html
title: Fowey Art Trail
description: Map of exhibitors for this year's Art Trail in Fowey
url: https://foweyarttrail.com
author: Hazel Bradish
